import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Altamira Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className={`${inter.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
